# Generated by Django 3.0 on 2019-12-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Golfcoursetbl',
            fields=[
                ('courseid', models.AutoField(db_column='courseID', primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_column='courseName', max_length=45)),
                ('coursehindex', models.FloatField(db_column='courseHIndex')),
                ('coursepar', models.IntegerField(blank=True, db_column='coursePar', null=True)),
            ],
            options={
                'db_table': 'golfCourseTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playerstbl',
            fields=[
                ('playerid', models.AutoField(db_column='playerID', primary_key=True, serialize=False)),
                ('playerfname', models.CharField(blank=True, db_column='playerFName', max_length=32, null=True)),
                ('playerlname', models.CharField(blank=True, db_column='playerLName', max_length=32, null=True)),
            ],
            options={
                'db_table': 'playersTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roundstbl',
            fields=[
                ('roundid', models.AutoField(db_column='roundID', primary_key=True, serialize=False)),
                ('roundscore', models.IntegerField(db_column='roundScore')),
            ],
            options={
                'db_table': 'roundsTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teestbl',
            fields=[
                ('teeid', models.AutoField(db_column='teeID', primary_key=True, serialize=False)),
                ('teecolour', models.CharField(db_column='teeColour', max_length=6)),
            ],
            options={
                'db_table': 'teesTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teeyardstbl',
            fields=[
                ('teeid', models.OneToOneField(db_column='teeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calc.Teestbl')),
                ('gcsloperate', models.FloatField(db_column='gcSlopeRate')),
                ('gccourserate', models.FloatField(blank=True, db_column='gcCourseRate', null=True)),
            ],
            options={
                'db_table': 'teeYardsTbl',
                'managed': False,
            },
        ),
    ]
